export const ORDER_STATUS = {
  DRAFT: 'DRAFT',
  QR_GENERATED: 'QR_GENERATED',
  STAFF_CONFIRM_PENDING: 'STAFF_CONFIRM_PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  READY_FOR_SERVICE: 'READY_FOR_SERVICE',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const QR_STATUS = {
  DRAFT: 'DRAFT',
  GENERATED: 'GENERATED',
  STAFF_CONFIRM_PENDING: 'STAFF_CONFIRM_PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];
export type QrStatus = (typeof QR_STATUS)[keyof typeof QR_STATUS];
