export const BRANCH_ROLES = {
  BUSINESS_ADMIN: 'BUSINESS_ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  STAFF: 'STAFF',
} as const;

export const STAFF_PERMISSIONS = {
  QR_CONFIRM: 'QR_CONFIRM',
  ORDER_STATUS_UPDATE_ANY: 'ORDER_STATUS_UPDATE_ANY',
  ORDER_STATUS_PREPARING: 'ORDER_STATUS_PREPARING',
  ORDER_STATUS_READY_FOR_SERVICE: 'ORDER_STATUS_READY_FOR_SERVICE',
  ORDER_STATUS_DELIVERED: 'ORDER_STATUS_DELIVERED',
  ORDER_STATUS_COMPLETED: 'ORDER_STATUS_COMPLETED',
  ORDER_STATUS_CANCELLED: 'ORDER_STATUS_CANCELLED',
  BRANCH_MEMBERSHIP_MANAGE: 'BRANCH_MEMBERSHIP_MANAGE',
  INVENTORY_WRITE: 'INVENTORY_WRITE',
  SHIFT_MANAGE: 'SHIFT_MANAGE',
} as const;

export type BranchRole = (typeof BRANCH_ROLES)[keyof typeof BRANCH_ROLES];
export type StaffPermission =
  (typeof STAFF_PERMISSIONS)[keyof typeof STAFF_PERMISSIONS];
